server:
  port: 8080

spring:
  application:
    name: sensorgroup
  data:
    mongodb:
      uri: mongodb://localhost:27017/sensorgroup
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    defaults:
      enabled: false
    mongo:
      enabled: false
